amcl:
  ros__parameters:
    # Reduced motion noise for better precision
    alpha1: 0.05  # Rotation noise from rotation
    alpha2: 0.05  # Rotation noise from translation  
    alpha3: 0.05  # Translation noise from translation
    alpha4: 0.05  # Translation noise from rotation
    alpha5: 0.02  # Translation noise
    
    base_frame_id: "agv1/base_link"
    
    # Enable beam skipping for robustness against dynamic obstacles
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5  # Lower for more aggressive skipping
    beam_skip_threshold: 0.3
    do_beamskip: true  # Enable for better handling of unexpected obstacles
    
    global_frame_id: "map"
    lambda_short: 0.1
    
    # Improved laser model parameters
    laser_likelihood_max_dist: 4.0  # Increased for better long-range matching
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    
    # Increased beams for better precision
    max_beams: 120  # Double the beams for higher accuracy
    
    # Optimized particle count for speed vs accuracy balance
    max_particles: 3000  # Increased for better precision
    min_particles: 200   # Reduced minimum for faster convergence
    
    odom_frame_id: "odom"
    
    # Tighter particle filter parameters for precision
    pf_err: 0.01  # Reduced for higher precision requirement
    pf_z: 0.99
    
    # Enable adaptive resampling for faster convergence
    recovery_alpha_fast: 0.1   # Enable fast recovery
    recovery_alpha_slow: 0.001 # Enable slow recovery
    
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 2.0  # Increased for more frequent pose updates
    
    # Improved sensor model parameters
    sigma_hit: 0.1  # Reduced for more precise laser matching
    
    tf_broadcast: true
    transform_tolerance: 0.5  # Reduced for stricter timing
    
    # More frequent updates for faster response
    update_min_a: 0.1   # Reduced for more frequent angular updates
    update_min_d: 0.1   # Reduced for more frequent translational updates
    
    # Optimized sensor model weights for precision
    z_hit: 0.8    # Increased weight on good hits
    z_max: 0.02   # Reduced weight on max range readings
    z_rand: 0.1   # Reduced random noise weight
    z_short: 0.08 # Slightly increased for obstacle handling
    
    scan_topic: scan
    
    # Additional parameters for improved performance
    # initial_pose_x: -3.93
    # initial_pose_y: -15.984
    # initial_pose_a: 0.0
    # initial_cov_xx: 0.25
    # initial_cov_yy: 0.25
    # initial_cov_aa: 0.1
    
    # Set selective resampling threshold
    selective_resampling: true
    
    # Force update on first message
    first_map_only: false
    
    # Improved KLD sampling parameters
    kld_err: 0.01
    kld_z: 0.99

    set_initial_pose: false
    
    # Set max particle weight for numerical stability
    max_weight_ratio: 1000.0