agv1/amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.02
    base_frame_id: agv1/base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    kld_err: 0.01
    kld_z: 0.99
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 120
    max_particles: 2000
    max_weight_ratio: 1000.0
    message_timeout_margin: 1.0
    min_particles: 500
    odom_frame_id: agv1/odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 2.0
    scan_topic: scan
    selective_resampling: true
    set_initial_pose: false
    sigma_hit: 0.1
    tf_broadcast: true
    tf_buffer_duration: 30.0
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.8
    z_max: 0.02
    z_rand: 0.1
    z_short: 0.08
agv2/amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.02
    base_frame_id: agv2/base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    kld_err: 0.01
    kld_z: 0.99
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 120
    max_particles: 2000
    max_weight_ratio: 1000.0
    message_timeout_margin: 1.0
    min_particles: 500
    odom_frame_id: agv2/odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 2.0
    scan_topic: scan
    selective_resampling: true
    set_initial_pose: false
    sigma_hit: 0.1
    tf_broadcast: true
    tf_buffer_duration: 30.0
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.8
    z_max: 0.02
    z_rand: 0.1
    z_short: 0.08
agv3/amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.02
    base_frame_id: agv3/base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    kld_err: 0.01
    kld_z: 0.99
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 120
    max_particles: 2000
    max_weight_ratio: 1000.0
    message_timeout_margin: 1.0
    min_particles: 500
    odom_frame_id: agv3/odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 2.0
    scan_topic: scan
    selective_resampling: true
    set_initial_pose: false
    sigma_hit: 0.1
    tf_broadcast: true
    tf_buffer_duration: 30.0
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.8
    z_max: 0.02
    z_rand: 0.1
    z_short: 0.08
agv4/amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.02
    base_frame_id: agv4/base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    kld_err: 0.01
    kld_z: 0.99
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 120
    max_particles: 2000
    max_weight_ratio: 1000.0
    message_timeout_margin: 1.0
    min_particles: 500
    odom_frame_id: agv4/odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 2.0
    scan_topic: scan
    selective_resampling: true
    set_initial_pose: false
    sigma_hit: 0.1
    tf_broadcast: true
    tf_buffer_duration: 30.0
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.8
    z_max: 0.02
    z_rand: 0.1
    z_short: 0.08
agv5/amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.02
    base_frame_id: agv5/base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    first_map_only: false
    global_frame_id: map
    kld_err: 0.01
    kld_z: 0.99
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 120
    max_particles: 2000
    max_weight_ratio: 1000.0
    message_timeout_margin: 1.0
    min_particles: 500
    odom_frame_id: agv5/odom
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 2.0
    scan_topic: scan
    selective_resampling: true
    set_initial_pose: false
    sigma_hit: 0.1
    tf_broadcast: true
    tf_buffer_duration: 30.0
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.8
    z_max: 0.02
    z_rand: 0.1
    z_short: 0.08
